import type { CSSProperties } from 'react'

export const editableRootStyle = {
  '--slot4-page-bg': '#fff5f7',
  '--slot4-page-text': '#27131b',
  '--slot4-panel-bg': '#f4f7fb',
  '--slot4-surface-bg': '#ffffff',
  '--slot4-muted-text': '#7d5a68',
  '--slot4-soft-muted-text': '#a07f8c',
  '--slot4-accent': '#fb5a72',
  '--slot4-accent-fill': '#fb5a72',
  '--slot4-accent-soft': '#ffe7ec',
  '--slot4-on-accent': '#ffffff',
  '--slot4-dark-bg': '#1f1b22',
  '--slot4-dark-text': '#ffffff',
  '--slot4-media-bg': '#e8edf4',
  '--slot4-cream': '#fff9fb',
  '--slot4-warm': '#eef3f8',
  '--slot4-lavender': '#fff1f5',
  '--slot4-gray': '#f6f8fb',
  '--slot4-brand-2': '#fb8b24',
  '--slot4-brand-3': '#e36414',
  '--slot4-brand-4': '#9a031e',
  '--slot4-brand-blue': '#1f7de3',
  '--slot4-body-gradient':
    'radial-gradient(circle at top, rgba(251,90,114,0.08), transparent 30%), linear-gradient(180deg, #fff7f9 0%, #f9fbff 42%, #fff7f8 100%)',
  '--editable-page-bg': '#fff5f7',
  '--editable-page-text': '#27131b',
  '--editable-container': '1220px',
  '--editable-border': '#ecd7de',
  '--editable-nav-bg': '#fb5a72',
  '--editable-nav-text': '#ffffff',
  '--editable-nav-active': '#ffffff',
  '--editable-nav-active-text': '#fb5a72',
  '--editable-cta-bg': '#ffffff',
  '--editable-cta-text': '#fb5a72',
  '--editable-search-bg': '#ffffff',
  '--editable-footer-bg': '#1f1b22',
  '--editable-footer-text': '#ffffff',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent-soft)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-white/10',
  shadow: 'shadow-[0_14px_36px_rgba(84,22,44,0.08)]',
  shadowStrong: 'shadow-[0_24px_80px_rgba(53,12,28,0.16)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(0,0,0,0.02),rgba(0,0,0,0.72))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-[var(--editable-container)] px-4 sm:px-6 lg:px-8',
    sectionY: 'py-14 sm:py-16 lg:py-20',
  },
  layout: {
    safeGrid: 'grid gap-6 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-10 lg:grid-cols-[1.06fr_0.94fr] lg:items-center',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[220px] shrink-0 snap-start sm:w-[250px]',
  },
  type: {
    eyebrow: 'text-[11px] font-bold uppercase tracking-[0.28em] text-[var(--slot4-accent)]',
    heroTitle: 'text-4xl font-bold leading-[1.02] tracking-[-0.04em] sm:text-5xl lg:text-[3.6rem]',
    sectionTitle: 'text-3xl font-bold tracking-[-0.03em] sm:text-4xl',
    body: 'text-base leading-relaxed',
  },
  surface: {
    card: `rounded-[28px] border ${editablePalette.border} ${editablePalette.surfaceBg} ${editablePalette.shadow}`,
    soft: `rounded-[26px] border ${editablePalette.border} ${editablePalette.panelBg}`,
    dark: `rounded-[28px] ${editablePalette.darkBg} ${editablePalette.darkText} ${editablePalette.shadowStrong}`,
  },
  button: {
    primary: `inline-flex items-center justify-center gap-2 rounded-full bg-[var(--slot4-accent-fill)] px-6 py-3 text-sm font-bold tracking-[0.01em] text-[var(--slot4-on-accent)] transition duration-200 hover:-translate-y-0.5 hover:brightness-95 active:scale-[0.98]`,
    secondary: `inline-flex items-center justify-center gap-2 rounded-full border border-[var(--editable-border)] bg-[var(--slot4-surface-bg)] px-6 py-3 text-sm font-bold tracking-[0.01em] text-[var(--slot4-page-text)] transition duration-200 hover:border-[var(--slot4-accent)] hover:text-[var(--slot4-accent)] active:scale-[0.98]`,
    accent: `inline-flex items-center justify-center gap-2 rounded-full ${editablePalette.accentBg} px-6 py-3 text-sm font-bold text-[var(--slot4-on-accent)] transition duration-200 hover:-translate-y-0.5 hover:brightness-95 active:scale-[0.98]`,
  },
  media: {
    frame: `relative overflow-hidden rounded-[24px] ${editablePalette.mediaBg}`,
    ratio: 'aspect-[4/3]',
  },
  motion: {
    lift: 'transition duration-300 hover:-translate-y-1.5 hover:shadow-[0_18px_48px_rgba(64,24,38,0.18)]',
    fade: 'transition duration-300 hover:opacity-80',
  },
} as const

export const aiLayoutRules = [
  'Change the full site color palette in editableRootStyle first; all homepage sections consume those CSS variables.',
  'Keep page structure in src/editable/sections/HomeSections.tsx so AI can redesign the whole home experience in one file.',
  'Use wide readable grids; never create skinny columns for paragraphs or cards.',
  'Mix featured, compact, horizontal, editorial, and image-first cards instead of repeating one pattern.',
  'Keep dynamic post fetching intact; do not replace posts with mock arrays.',
  'Use postHref() for all post links so task-specific routes keep working.',
] as const
